heat_template_version: 2015-10-15

parameters:
  NeutronAgentPluginVolumes:
    type: comma_delimited_list
    default: ["foo"]
  NeutronAgentOvsVolumes:
    type: comma_delimited_list
    default: []

outputs:
  volumes:
    value:
      str_split:
        - ","
        - list_join:
           - ","
           -
             - /run:/run
             - /lib/modules:/lib/modules:ro
             - /var/lib/etc-data/json-config/neutron-agent.json:/var/lib/kolla/config_files/config.json
             - /var/lib/etc-data/neutron/neutron.conf:/var/lib/kolla/config_files/neutron.conf:ro
           - {get_param: NeutronAgentPluginVolumes}
           - {get_param: NeutronAgentOvsVolumes}
