heat_template_version: 2015-04-30

parameters:
  servers:
    type: json

resources:
  DatabaseConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/sh
        echo "I am database!" > /tmp/database_role

  DatabaseDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: DatabaseConfig}
