heat_template_version: 2015-04-30

parameters:
  servers:
    type: json

resources:
  KeystoneConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/sh
        echo "I am keystone!" > /tmp/keystone_role

  KeystoneDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: KeystoneConfig}
